<a href="https://colab.research.google.com/github/RAGHUL-K-R/PYTHON/blob/main/UNIT_5_EXERCISE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random

### Write a code to generate the following series
![image.png](attachment:image.png)

In [ ]:
s = pd.Series([0,7,14,21,28,35,42,49,56,63,70,77,84,91,98])
arr = np.random.randint(7, size=(3, 3))
print(arr)

[[1 0 6]
 [1 1 5]
 [3 4 6]]


### Write a Code to convert a 1-D array to a 3-D array
![image.png](attachment:image.png)

In [ ]:
a = np.arange(27)
b = a.reshape(3,3,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### Combine the given two arrays as below

**Given Array**

![image-2.png](attachment:image-2.png)

**Resultant Array**

![image.png](attachment:image.png)

### Generate of given count of equally spaced 10 numbers within a range of 0 to 100

![image.png](attachment:image.png)

### Generate the matrix of with 5 rows and 5 columns and assign to one value "999"

### Generate the series as below

![image.png](attachment:image.png)


In [ ]:
Jan = pd.Series([26,48,65,64,88],index=["Drygrapes","Cashew","Walnut","Fig","Dates"],name="Jan Month Sales of Dry Fruits")
Feb = pd.Series([50,38,62,78,93],index=["Drygrapes","Cashew","Walnut","Fig","Dates"],name="Feb Month Sales of Dry Fruits")
print(Jan)
print(Feb)

### Find the sales difference of two months Jan and Feb and generate the output as below

![image.png](attachment:image.png)

### Display the Dryfruits that have an increased its sales in the Feb month compared to Jan month

![image.png](attachment:image.png)

## Calculate the percentage of increase in sales

**Formula = (Sales in Jan month - Sales in Feb Month)/Sales of Feb month * 100**

And Display the result as below

![image.png](attachment:image.png)

### Use the above generate series and generate the below dataframe.

![image.png](attachment:image.png)


### Rename the column name of Percentage of sales as below.

![image.png](attachment:image.png)

### Replace the NAN values with '0' as below

![image.png](attachment:image.png)

### Round of the profit percentage to two decimal values as below.

![image.png](attachment:image.png)

## Generate the Dataframe as below which describes about the step count of 5 persons.

![image.png](attachment:image.png)

## Add the column "Total Step count" as below which consist of total step count for 7 days and if the sum value is float convert that to integer

![image.png](attachment:image.png)

## Calculate the average step count for each person as below

![image.png](attachment:image.png)

## Average step count need to rounded off to one decimal and add it as a new column to the dataframe.

![image.png](attachment:image.png)

## Find the minimum step count of each person and which has to be added as the new column to the dataframe it type must be an integer

![image.png](attachment:image.png)

##  Find the maximum step count of each person and which has to be added as the new column to the dataframe it type must be an integer

![image.png](attachment:image.png)

## Display the name of the person whose average step count is minimum.

![image.png](attachment:image.png)

________________________________________________

# Load the student database "student_exercise"

## Display the columns of the dataframes

## Display the descriptive statistics of numeric columns in the DataFrame

## Display the details of top 5 student based on their marks

## Display the first 5 records of NAME column of the DataFrame

## filter rows where the "Mark" column is greater than 60

## fill missing values with a specific value or with zero

## filter rows where the "class" column is Three and the "mark" column is More than 50.

## Display the total number of missing values in each column

## Randomly select 7 rows (sample) from a DataFrame